version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - gocyclo
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
    - nilerr
    - nilnesserr
    - nilnil
    - errorlint
#    - err113
  settings:
    revive:
      enable-all-rules: false
      rules:
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ""
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - unused
        path: state/trie/node.go
      - linters:
          - unused
        path: state/trie/node_enc.go
      - linters:
          - unused
        path: state/trie/encoding.go
      - linters:
          - unused
        path: portalwire/table_util_test.go
      - linters:
          - unparam
          - unused
        path: portalwire/table.go
      - linters:
          - unparam
        path: portalwire/table_test.go
      - linters:
          - unparam
        path: portalwire/table_reval.go
      - linters:
          - unused
        path: portalwire/lookup.go
      - linters:
          - unparam
        path: state/trie/node_test.go
      - linters:
          - nilerr
        path: portalwire/portal_protocol.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

run:
  timeout: 10m